<?php
$value = array (
  'wwwprefix' => 'http://www.xuelu.org/hm',
  'imgprefix' => 'http://www.xuelu.org/hm',
  'cssprefix' => 'http://www.xuelu.org/hm',
  'sitename' => 'Happer Makeup',
  'sitetitle' => '',
  'abbreviation' => 'Happer Makeup',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
);
?>